# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 12:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=1024, null=True)),
                ('title', models.CharField(blank=True, max_length=2048)),
                ('description', models.TextField(blank=True, null=True)),
                ('license', models.CharField(max_length=1024, null=True)),
                ('url', models.CharField(max_length=2048, null=True)),
                ('raw_data', models.TextField()),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('language', models.CharField(max_length=512, null=True)),
                ('partner', models.CharField(max_length=1024)),
                ('store_type', models.CharField(max_length=1024)),
                ('keywords', models.TextField(null=True)),
                ('location', models.CharField(max_length=1024, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(default='')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='sti_store_search__e2e597_gin'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['language'], name='sti_store_languag_446771_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['partner'], name='sti_store_partner_bbcb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_type'], name='sti_store_store_t_e315ee_idx'),
        ),
    ]
