# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 11:44
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=2048)),
                ('description', models.TextField()),
                ('fulltext', models.TextField()),
                ('license', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=2048)),
                ('raw_data', models.TextField()),
                ('language', models.CharField(max_length=512)),
                ('source', models.CharField(max_length=1024)),
                ('partner', models.CharField(max_length=1024)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(default='')),
            ],
        ),
    ]
