# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 06:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=1024, null=True)),
                ('title', models.CharField(blank=True, max_length=2048)),
                ('description', models.TextField(blank=True, null=True)),
                ('license', models.CharField(max_length=1024, null=True)),
                ('url', models.CharField(max_length=2048, null=True)),
                ('raw_data', models.TextField()),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('language', models.CharField(max_length=512, null=True)),
                ('partner', models.CharField(max_length=1024)),
                ('store_type', models.CharField(max_length=1024)),
                ('keywords', models.TextField(null=True)),
                ('location', models.CharField(max_length=1024, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(default='')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
