# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 11:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=128, unique=True)),
                ('keyval', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
